# Generated by Django 4.2.6 on 2023-11-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_goal_category_alter_goal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('achieved', 'Achieved')], default='not_started', max_length=20),
        ),
    ]
