# Generated by Django 4.2.6 on 2023-10-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_goal_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('professional', 'Professional'), ('personal', 'Personal'), ('development', 'Development'), ('ministry', 'Ministry'), ('health', 'Ministry')], max_length=20),
        ),
    ]
