# Generated by Django 4.2.6 on 2023-10-20 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_goal_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='linked_goals',
        ),
        migrations.AddField(
            model_name='activity',
            name='linked_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.goal'),
        ),
    ]
