# Generated by Django 3.2.8 on 2023-11-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_goal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='achieved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
