# Generated by Django 4.2.6 on 2023-11-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_activity_linked_goals_activity_linked_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='target_date',
            field=models.DateTimeField(null=True),
        ),
    ]
