# Generated by Django 4.2.6 on 2023-11-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_goal_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('faith', 'Faith'), ('financial', 'Financial'), ('personal', 'Personal'), ('development', 'Development'), ('professional', 'Professional')], max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='type',
            field=models.CharField(choices=[('long_term', 'Long Term (5-20 years)'), ('mid_term', 'Mid Term (1-5 years)'), ('short_term', 'Short Term (< 12 Months)')], max_length=20),
        ),
    ]
