# Generated by Django 4.2.6 on 2023-10-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_activity_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='summary',
        ),
    ]
