# Generated by Django 4.2.6 on 2023-10-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_activity_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='action_items',
            new_name='actions',
        ),
    ]
