# Generated by Django 4.2.6 on 2023-10-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_goal_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('professional', 'Professional'), ('personal', 'Personal'), ('development', 'Development'), ('faith', 'Faith'), ('charity', 'Charity')], max_length=20),
        ),
    ]
